---
version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./data_schema.sql:/docker-entrypoint-initdb.d/data_schema.sql
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      - POSTGRES_USER=${DBUSERNAME}
      - POSTGRES_PASSWORD=${DBPASSWORD}
  pe-reports:
    build: ./
    volumes:
      - ./:/usr/src/pe-reports/
    ports:
      - '5000:5000'
    networks:
      - backend
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
